HTTPConfig:
  Host:           "localhost"
  Port:           8080
  MaxHeaderBytes: 1
  ReadTimeout:    10s
  WriteTimeout:   10s

PostgresConfig:
  Host:     "localhost"
  Port:     "5432"
  Username: "admin"
  Password: "123456"
  DBName:   "orders"
  SSLMode:  "disable"

RouterConfig:
  Host:     "localhost"
  Port:     "12345"
  VCopter:  "20"
  MaxDistanceCopter: "1"
  TimeWaitOrder: "0"

HubsConfig:
  Host:     "127.0.0.1"
  BasePort: 18000