http:
  Host: "localhost"
  Port: 8000
  MaxHeaderBytes: 1
  ReadTimeout: 10s
  WriteTimeout: 10s

postgres:
  Host:     "localhost"
  Port:     "5436"
  Username: "postgres"
  Password: "123"
  DBName:   "postgres"
  SSLMode:  "disable"
